spring:
  application:
    name: Passbook
  datasource:
    url: jdbc:mysql://106.14.183.86/passbook?autoReconnect=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 106.14.183.86:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 106.14.183.86:2181
      rootDir: /
      nodeParent: /hbase
  redis:
    host: 106.14.183.86
    port: 6379
server:
  port: 9528
logging:
  file: passbook.log
  level: debug
